const SEED_TRIP_DATA = {
  name: "המסלול של דולב ונועה",
  customers: "דולב ונועה",
  start_date: "2026-03-17",
  end_date: "2026-04-07",
  days: [
    {
      id: "day-1", date: "2026-03-17", dayOfWeek: "שלישי", title: "הגעה לאוסקה", city: "אוסקה", cityEn: "Osaka", color: "#FF6B35",
      hotel: { name: "Candeo Hotels Osaka Shinsaibashi", mapsQuery: "Candeo+Hotels+Osaka+Shinsaibashi+Japan" },
      items: [
        { id:"d1-a1", type:"activity", time:"11:00", emoji:"✈", title:"נחיתה בנמל התעופה קנסאי", titleEn:"Kansai International Airport", mapsQuery:"Kansai+International+Airport+Japan", description:"נחיתה לאחר טיסה מדובאי. הגעה לנמל התעופה קנסאי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d1-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לאוסקה", titleEn:"Nankai Express", mapsQuery:null, description:"מעבר משדה התעופה למרכז העיר", fee:null, bookInAdvance:false, line:"NANKAI EXPRESS", from:"Kansai Airport", to:"Namba Station", duration:"~שעה", transportNote:"הנפקת כרטיס IC נסיעה בתחנה לצורך התניידות ביפן" },
        { id:"d1-a2", type:"activity", time:"", emoji:"🏨", title:"צ'ק אין במלון", titleEn:"Candeo Hotels Osaka Shinsaibashi", mapsQuery:"Candeo+Hotels+Osaka+Shinsaibashi+Japan", description:"", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d1-r1", type:"restaurant", time:"", emoji:"🍜", title:"שוק Kuromon Ichiba Market", titleEn:"Kuromon Ichiba Market", mapsQuery:"Kuromon+Ichiba+Market+Osaka+Japan", description:"שוק מקורה שהמקומיים מכנים אותו 'המטבח של אוסקה'. דוכני אוכל רחוב, פירות טריים, דגים ופירות ים, ואווירה מקומית. נסגר בסביבות 18:00", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d1-a3", type:"activity", time:"", emoji:"🎮", title:"Nipponbashi Den Den Town", titleEn:"Nipponbashi Den Den Town", mapsQuery:"Nipponbashi+Den+Den+Town+Osaka+Japan", description:"האקיהברה של אוסקה – אזור מלא חנויות אנימה, מנגה, פיגורינות, משחקי וידאו ואלקטרוניקה. אווירה צבעונית וצעירה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d1-a4", type:"activity", time:"", emoji:"⛩", title:"מקדש נמבה יאסאקה", titleEn:"Namba Yasaka Shrine", mapsQuery:"Namba+Yasaka+Shrine+Osaka+Japan", description:"מקדש קטן אבל ייחודי – מבנה ענק בצורת ראש אריה עם פה פתוח, שמסמל הגנה ומזל טוב. המקומיים מאמינים שהפה 'בולע את הרוע'. מקום שקט יותר אחרי ההמולה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d1-a5", type:"activity", time:"", emoji:"🛍", title:"שינסיבאשי & דוטונבורי", titleEn:"Dotonbori Osaka", mapsQuery:"Dotonbori+Osaka+Japan", description:"הלב של אוסקה – רחוב שינסיבאשי עם חנויות אופנה בינלאומיות ומותגים מקומיים, ודוטונבורי עם שלטי ניאון עצומים, דוכני אוכל רחוב. לעצור ליד שלט Glico Man האייקוני ולהצטלם", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["הנפקת כרטיס IC בתחנה לצורך התניידות ביפן", "אם מספיקים להגיע ישר אחרי השדה לפני שהולכים לדוטונבורי, שוק קורומון נסגר ב-18:00"],
      appendix: []
    },
    {
      id: "day-2", date: "2026-03-18", dayOfWeek: "רביעי", title: "אוסקה הקולינרית", city: "אוסקה", cityEn: "Osaka", color: "#FF6B35",
      hotel: { name: "Candeo Hotels Osaka Shinsaibashi", mapsQuery: "Candeo+Hotels+Osaka+Shinsaibashi+Japan" },
      items: [
        { id:"d2-a1", type:"activity", time:"", emoji:"🍳", title:"סדנת בישול ביתית אצל Keiko", titleEn:"Keiko Cooking Class Osaka", mapsQuery:"Momoyamadai+Station+Osaka+Japan", description:"בנסיעה בקו M הצפוני לתחנת Momoyamadai. במהלך הסדנא תבשלו ראמן, גיוזה ומתוקים יפניים – חוויה!", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה חזרה למרכז", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Metro", from:"Momoyamadai", to:"Tanimachi 4-chome", duration:"~30 דקות", transportNote:"ממשיכים ל-Sakaisuji Hommachi Station ומשם Tanimachi 4-chome Station" },
        { id:"d2-a2", type:"activity", time:"", emoji:"🏯", title:"מצודת אוסקה", titleEn:"Osaka Castle", mapsQuery:"Osaka+Castle+Japan", description:"הליכה דרך הפארק למצודת אוסקה – אחת הטירות המפורסמות והמרשימות ביפן, עם נוף מדהים של העיר וגנים יפים מסביב. אחד הסמלים הכי חזקים של העיר, גם ויזואלית, גם היסטורית", fee:{amount:600,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-a3", type:"activity", time:"", emoji:"🗼", title:"תצפית מאומדה", titleEn:"Umeda Sky Building", mapsQuery:"Umeda+Sky+Building+Osaka+Japan", description:"מצפה פנורמי בגובה 173 מטרים עם נוף עוצר נשימה של העיר והרים מרוחקים", fee:{amount:1500,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-r1", type:"restaurant", time:"", emoji:"🍽", title:"ארוחת צהריים באומדה", titleEn:"Umeda Osaka Restaurants", mapsQuery:"Umeda+Osaka+Japan", description:"ארוחת צהריים באזור אומדה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-a4", type:"activity", time:"", emoji:"🛍", title:"Tenjinbashisuji – רחוב הקניות הארוך ביפן", titleEn:"Tenjinbashisuji Shopping Street", mapsQuery:"Tenjinbashisuji+Shopping+Street+Osaka+Japan", description:"רחוב קניות מקורה שמתפרש על פני 7 אזורים, 2.6 קילומטרים! חנויות יפניות ממש מכל הסוגים והמחירים עממיים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-a5", type:"activity", time:"17:30", emoji:"🏮", title:"סיור קולינרי בשינסאקאי", titleEn:"Shinsekai Osaka", mapsQuery:"Shinsekai+Osaka+Japan", description:"יורדים בתחנת Dobutsuen-Mae. רובע נוסטלגי עם אווירה יפנית מסורתית, מסעדות רחוב מפורסמות ומגדל צוטנקאקו האייקוני. הסיור מתמקד בגסטרונומיה, בירות ואלכוהול מקומי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-r2", type:"restaurant", time:"", emoji:"🍶", title:"Bar Nayuta", titleEn:"Bar Nayuta Osaka", mapsQuery:"Bar+Nayuta+Osaka+Japan", description:"בר קוקטיילים ניחוח יפני באווירה ייחודית – המלצה שלי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-a6", type:"activity", time:"", emoji:"♨", title:"Spa World", titleEn:"Spa World Osaka", mapsQuery:"Spa+World+Osaka+Japan", description:"מתחם ענק של 8 קומות שמוקדש לרוגע – מים חמים, סאונות, בריכות, טיפולים. כניסה ¥1500 בלבד, פתוח 24/7. המלצה: טיפול קרצוף קוריאני – מטורף!", fee:{amount:1500,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["מומלץ בחום לפני החזרה – טיפול קרצוף קוריאני במתחם Spa World"],
      appendix: [
        { id:"d2-x1", type:"activity", time:"", emoji:"🎭", title:"אמריקאמורה", titleEn:"Amerikamura Osaka", mapsQuery:"Amerikamura+Osaka+Japan", description:"עירוב אופנתי ואמנותי בסגנון רחוב אמריקאי, עם חנויות וינטג', אופנת רחוב, אמנות גרפיטי ומוזיקה חיה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-x2", type:"activity", time:"", emoji:"🎮", title:"Round1 Stadium Sennichimae", titleEn:"Round1 Stadium Sennichimae Osaka", mapsQuery:"Round1+Stadium+Sennichimae+Osaka+Japan", description:"המשחקיה הכי משוגעת באוסקה – קריוקי, באולינג, חדרי צילום יפניים, סימולטורים, ריקוד, ספורט וירטואלי, מכות, מירוצים – הכל!", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d2-x3", type:"activity", time:"", emoji:"🎉", title:"מועדונים – Giraffe Osaka / Club Joule", titleEn:"Giraffe Osaka Club", mapsQuery:"Giraffe+Osaka+Club+Japan", description:"מוזיקה חזקה, לייזרים, קהל יפני צעיר בטירוף. או – שיטוט בין הברים הקטנים של דוטונבורי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ]
    },
    {
      id: "day-3", date: "2026-03-19", dayOfWeek: "חמישי", title: "יוניברסל סטודיוס יפן", city: "אוסקה", cityEn: "Osaka", color: "#FF6B35",
      hotel: { name: "Candeo Hotels Osaka Shinsaibashi", mapsQuery: "Candeo+Hotels+Osaka+Shinsaibashi+Japan" },
      items: [
        { id:"d3-a1", type:"activity", time:"", emoji:"🍳", title:"ארוחת בוקר והתארגנות", titleEn:"", mapsQuery:null, description:"לקראת יום של אקשן וסרטים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d3-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה ליוניברסל", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"JR Yumesaki Line", from:"Umeda Station", to:"Universal City", duration:"~30 דקות", transportNote:"להגיע לתחנת UMEDA ומשם להחליף לאקספרס/JR Yumesaki Line" },
        { id:"d3-a2", type:"activity", time:"", emoji:"🎮", title:"Super Nintendo World", titleEn:"Super Nintendo World USJ", mapsQuery:"Super+Nintendo+World+Universal+Studios+Japan", description:"המתחם הכי חדש והכי מדובר בפארק – חובה להזמין כניסה מראש! חוויית מריו קארט ב-VR ברמה שלא תיאמן, ומסלול רגוע של Yoshi's Adventure עם תצפיות", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d3-a3", type:"activity", time:"", emoji:"🎢", title:"The Flying Dinosaur", titleEn:"The Flying Dinosaur USJ", mapsQuery:"Universal+Studios+Japan", description:"רכבת הרים מטורפת בתנוחת 'מעוף' – אחת האטרקציות הכי קיצוניות בפארק", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d3-a4", type:"activity", time:"", emoji:"🦖", title:"Jurassic Park: The Ride", titleEn:"Jurassic Park The Ride USJ", mapsQuery:"Universal+Studios+Japan", description:"שייט שקט שמסתיים בנפילה מפתיעה ישר מהדינוזאורים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d3-r1", type:"restaurant", time:"", emoji:"🍽", title:"הפסקת צהריים – Hollywood Boulevard", titleEn:"Hollywood Boulevard USJ", mapsQuery:"Universal+Studios+Japan", description:"המון מסעדות במתחם, כולל אוכל מערבי ומסעדות נושא", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d3-a5", type:"activity", time:"", emoji:"🎬", title:"מופע WATERWORLD", titleEn:"Waterworld USJ", mapsQuery:"Universal+Studios+Japan", description:"חוויה שלא ניתנת להסבר במילים – וואו וואו וואו. הכינו מצלמות! חובה להגיע לפחות 25 דקות קודם בימים עמוסים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d3-a6", type:"activity", time:"", emoji:"🌌", title:"עולם הארי פוטר", titleEn:"Wizarding World Harry Potter USJ", mapsQuery:"Universal+Studios+Japan", description:"תסתובבו ברחובות הוגסמיד, תשתו Butterbeer, תיכנסו לחנות השרביטים של אוליבנדר. עלו על המתקן Forbidden Journey – האהוב עליי מכל המתקנים בפארק!", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d3-a7", type:"activity", time:"", emoji:"🎭", title:"מתקנים נוספים", titleEn:"", mapsQuery:"Universal+Studios+Japan", description:"Despicable Me Minion Mayhem – מתאים מאוד לילדים. Hollywood Dream – רכבת הרים עם מוזיקה לבחירה באוזניים, כולל אופציה לנסיעה לאחור!", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["להוריד מראש את האפליקציה של הפארק – רואים דרכה זמני המתנה, ניתן להזמין מקום לנינטנדו ולעדכן את האקספרס פס", "יש גם שירותי נגישות דומים לדיסני – עם פתק תור לשעת הגעה שתוכלו לקבל בשער או בעמדות שירות"],
      appendix: []
    },
    {
      id: "day-4", date: "2026-03-20", dayOfWeek: "שישי", title: "נפרדים מאוסקה לקויהסאן", city: "קויהסאן", cityEn: "Koyasan", color: "#795548",
      hotel: { name: "Ichijo-in Temple", mapsQuery: "Ichijoin+Temple+Koyasan+Japan" },
      items: [
        { id:"d4-a1", type:"activity", time:"", emoji:"🏨", title:"צ'ק אאוט מהמלון", titleEn:"", mapsQuery:null, description:"לא לשכוח לשלוח מזוודות לנארה! אפשר לשמור טרולי בתוך תחנת נמבה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d4-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לאיזור הנמל", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"CHUO Line", from:"Namba", to:"Osakako", duration:"~15 דקות", transportNote:"לעלות צפונה מנמבה לאחת התחנות שנמצאות על קו CHUO" },
        { id:"d4-a2", type:"activity", time:"", emoji:"🐠", title:"אקווריום קיוקיואן", titleEn:"Kaiyukan Aquarium", mapsQuery:"Kaiyukan+Aquarium+Osaka+Japan", description:"פותחים את היום באחד האקווריומים הכי מרשימים בעולם! הבניין עצמו עצום, והסיור יורד בצורה ספירלית דרך אזורים ימיים מכל העולם. הכוכב של המקום הוא כריש לווייתן ענק. כשלוש שעות", fee:{amount:2700,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d4-r1", type:"restaurant", time:"", emoji:"🍡", title:"Tempozan Marketplace / Kuma Kafe", titleEn:"Kuma Kafe Osaka", mapsQuery:"Kuma+Kafe+Osaka+Japan", description:"מתחם מחוץ לאקווריום – מקום אחלה לארוחת בוקר קלה או נשנוש. Kuma Kafe – מסעדה בסגנון אמריקאי עם אוכל איכותי בעיצוב ושירות מדהים, אחד המקומות המומלצים בכל אוסקה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d4-t2", type:"transport", time:"", emoji:"🚆", title:"מסע לקויהסאן – רכבת, רכבל, אוטובוס", titleEn:"", mapsQuery:null, description:"הדרך היא חוויה בפני עצמה", fee:null, bookInAdvance:false, line:"Nankai Koya Line", from:"Nankai Namba Station", to:"Gokurakubashi", duration:"שעה וחצי", transportNote:"שימו לב – לא JR! יוצאים מתחנת Nankai Namba Station. עם כרטיס Koyasan World Heritage Ticket שכולל את הרכבת הלוך חזור, הרכבל ונסיעות חופשיות באוטובוסים בתוך קויסאן. תצטרכו להוסיף ~¥780 לרכבות Limited Express" },
        { id:"d4-t3", type:"transport", time:"", emoji:"🚠", title:"רכבל Cable Car", titleEn:"Koyasan Cable Car", mapsQuery:"Koyasan+Cable+Car+Japan", description:"בתחנת Gokurakubashi יורדים מהרכבת ועוברים מיד לרכבל (המעבר קל וברור). חוויה תלולה בטירוף!", fee:null, bookInAdvance:false, line:"Cable Car", from:"Gokurakubashi", to:"Koyasan", duration:"~5 דקות", transportNote:"ביציאה מתחנת הרכבל עולים על אוטובוס של חברת Nankai Rinkan Bus" },
        { id:"d4-a3", type:"activity", time:"", emoji:"⛩", title:"צ'ק אין במקדש", titleEn:"Ichijo-in Temple Koyasan", mapsQuery:"Ichijoin+Temple+Koyasan+Japan", description:"בקויה-סאן לא ישנים במלון רגיל, אלא במקדש! חוויה זו של פעם בחיים", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["הכרטיס Koyasan World Heritage Ticket חוסך המון כאב ראש – כולל הכל", "שימו לב – לא JR! יוצאים מ-Nankai Namba Station"],
      appendix: []
    },
    {
      id: "day-5", date: "2026-03-21", dayOfWeek: "שבת", title: "קויהסאן", city: "קויהסאן", cityEn: "Koyasan", color: "#795548",
      hotel: { name: "Ichijo-in Temple", mapsQuery: "Ichijoin+Temple+Koyasan+Japan" },
      items: [
        { id:"d5-a1", type:"activity", time:"06:00", emoji:"🔥", title:"טקס האש (Goma Fire Ritual)", titleEn:"Goma Fire Ritual Koyasan", mapsQuery:"Ichijoin+Temple+Koyasan+Japan", description:"השכמה מוקדמת (שווה את זה!). משתתפים בטקס הבוקר במקדש. הנזירים שורפים מקלות עץ עם משאלות בתוך להבות גבוהות לקול תיפוף ומנטרות. טקס מהפנט וחזק מאוד", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-r1", type:"restaurant", time:"", emoji:"🍳", title:"ארוחת בוקר במקדש", titleEn:"", mapsQuery:null, description:"ארוחת בוקר מסורתית במקדש", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-a2", type:"activity", time:"", emoji:"🪨", title:"גן הסלעים Banryutei", titleEn:"Banryutei Rock Garden Koyasan", mapsQuery:"Banryutei+Kongobuji+Koyasan+Japan", description:"גן הסלעים הגדול ביותר ביפן – מעוצב בצורה של שני דרקונים שבוקעים מתוך ים של עננים (חצץ לבן). מראה פוטוגני בטירוף. כשאני הייתי הכרטיס כלל תה ירוק ועוגייה מסורתית באולם קבלת הפנים הענק", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-r2", type:"restaurant", time:"", emoji:"🍽", title:"ארוחת צהריים – מסעדת Hanabishi", titleEn:"Hanabishi Restaurant Koyasan", mapsQuery:"Hanabishi+Restaurant+Koyasan+Japan", description:"מסעדה מומלצת באווירה מקומית. מומלץ להזמין את הבנטו המסורתי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-a3", type:"activity", time:"", emoji:"⛩", title:"מתחם Danjo Garan", titleEn:"Danjo Garan Koyasan", mapsQuery:"Danjo+Garan+Koyasan+Japan", description:"המתחם הדתי המרכזי. אי אפשר לפספס את הפגודה הכתומה (Konpon Daito) – הצבע שלה בולט למרחוק ויוצא מדהים בתמונות. תסתובבו בין המבנים, האנרגיה שם מיוחדת מאוד", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-r3", type:"restaurant", time:"", emoji:"🍽", title:"ארוחת ערב במקדש", titleEn:"", mapsQuery:null, description:"חוזרים למקדש לארוחת ערב מוקדמת. האוכל הוא מטבח נזירים טבעוני – חוויה קולינרית אחרת, המון צלוחיות קטנות, טופו שומשום שהוא המעדן המקומי, והכל אסתטי בטירוף. תבואו בראש פתוח", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-a4", type:"activity", time:"19:00", emoji:"🏮", title:"סיור לילה בבית הקברות Okunoin", titleEn:"Okunoin Cemetery Night Tour Koyasan", mapsQuery:"Okunoin+Cemetery+Koyasan+Japan", description:"אחת מגולות הכותרת של הביקור. יוצאים לסיור מודרך בבית הקברות העתיק ביפן. הליכה בין אלפי קברים עתיקים, עצים בני מאות שנים ופנסים דולקים בערפל. המדריך (נזיר) מספר את הסיפורים והסודות של המקום. אווירה מיסטית ומכשפת", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: [
        { id:"d5-x1", type:"activity", time:"", emoji:"⛩", title:"שער הענקים Daimon Gate", titleEn:"Daimon Gate Koyasan", mapsQuery:"Daimon+Gate+Koyasan+Japan", description:"שער הכניסה הראשי של ההר (גובה 25 מטר!). הנוף ממערב משם מגיע עד הים בימים בהירים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-x2", type:"activity", time:"", emoji:"🚶‍♂️", title:"מסלול הנשי ומקדש Nyonindo", titleEn:"Nyonindo Temple Koyasan", mapsQuery:"Nyonindo+Temple+Koyasan+Japan", description:"בעבר נשים לא הורשו להיכנס לקויה-סאן. ליד השער יש כניסה למסלול הליכה ביער – 20-30 דקות של הליכה קלילה בטבע ושקט מוחלט", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-x3", type:"activity", time:"", emoji:"🖼", title:"מוזיאון אוצרות בודהה Reihokan", titleEn:"Reihokan Museum Koyasan", mapsQuery:"Reihokan+Museum+Koyasan+Japan", description:"שומרים כאן את הפסלים המקוריים בני 1,000 שנה. פסלי עץ עצומים עם הבעות פנים מרגשות. הנחה בכניסה עם ה-World Heritage Ticket", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d5-x4", type:"activity", time:"", emoji:"🏯", title:"המאוזוליאום של השוגונים Tokugawa", titleEn:"Tokugawa Mausoleum Koyasan", mapsQuery:"Tokugawa+Mausoleum+Koyasan+Japan", description:"שני מבנים מפוארים שנבנו לכבוד השוגונים הכי חזקים בהיסטוריה של יפן. הרבה זהב, פיתוחים מורכבים ושקט מופתי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ]
    },
    {
      id: "day-6", date: "2026-03-22", dayOfWeek: "ראשון", title: "נארה – עיר האיילים", city: "נארה", cityEn: "Nara", color: "#4CAF50",
      hotel: { name: "Novotel Nara", mapsQuery: "Novotel+Nara+Japan" },
      items: [
        { id:"d6-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לנארה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Bus 65 + Train", from:"Koyasan", to:"Nara", duration:"~3 שעות", transportNote:"יוצאים מבית הארחה בבוקר. בקו 65 (אוטובוס) עד תחנת KAMO ומשם רכבת לתחנת נארה" },
        { id:"d6-a1", type:"activity", time:"", emoji:"🦌", title:"פארק נארה", titleEn:"Nara Park", mapsQuery:"Nara+Park+Japan", description:"מפגש עם האיילים החופשיים המטיילים בפארק – הליכה קצרה ואתם בלב הפארק הירוק עם איילים חופשיים שמסתובבים בין האנשים. אפשר לקנות להם עוגיות (Shika Senbei), להצטלם ולחוות את האווירה המיוחדת של נארה – עיר של קדושה וטבע יחד. (זמן חופשי עד שעה וחצי)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d6-a2", type:"activity", time:"", emoji:"⛩", title:"מקדש טודאי-ג'י", titleEn:"Todai-ji Temple", mapsQuery:"Todai-ji+Temple+Nara+Japan", description:"מקדש בודהיסטי מפורסם ובו פסל הבודהה הענק – אחד המבנים הכי מרשימים ביפן, כולו עץ, ובתוכו פסל בודהה בגובה 15 מטר. ביקור כ-45 דקות", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d6-a3", type:"activity", time:"", emoji:"🌳", title:"מקדש קאסוגה טאישה", titleEn:"Kasuga Taisha Shrine", mapsQuery:"Kasuga+Taisha+Shrine+Nara+Japan", description:"הולכים מהבודהה דרך שביל מקסים בתוך יער שינטו ירוק ושקט עם מאות פנסי אבן ומתכת שמובילים למקדש. מקום רגוע עם אווירה רוחנית", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d6-a4", type:"activity", time:"", emoji:"📸", title:"Ukimido – הביתן הצף", titleEn:"Ukimido Nara", mapsQuery:"Ukimido+Nara+Japan", description:"ביתן עץ מסורתי שבנוי ממש בתוך האגם. שמו ביפנית משמעותו 'הביתן שצף על פני המים' – במיוחד יפה לקראת שקיעה כשהשמש משתקפת במים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d6-a5", type:"activity", time:"", emoji:"🛍", title:"רחוב Higashimuki Shopping Street", titleEn:"Higashimuki Shopping Street Nara", mapsQuery:"Higashimuki+Shopping+Street+Nara+Japan", description:"רחוב קניות מקורה ממש דקה הליכה מתחנת Kintetsu-Nara – חנויות בגדים, מזכרות, קוסמטיקה יפנית, אוכל רחוב, בתי קפה, מסעדות סושי וקינוחים. לא להחמיץ את המוצ'י שנעשה בשיטה האותנטית ב-Nakatanidou", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["אפשר לסיים בקניון Mi Nara"],
      appendix: []
    },
    {
      id: "day-7", date: "2026-03-23", dayOfWeek: "שני", title: "וואזוקה – ממלכת התה", city: "וואזוקה", cityEn: "Wazuka", color: "#66BB6A",
      hotel: { name: "Novotel Nara", mapsQuery: "Novotel+Nara+Japan" },
      items: [
        { id:"d7-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לוואזוקה", titleEn:"", mapsQuery:null, description:"מחוץ למסלול השחוק (יציאה וחזרה מנארה)", fee:null, bookInAdvance:false, line:"Yamatoji Line + Shuttle", from:"JR Nara", to:"Kamo Station → Wazuka", duration:"~45 דקות", transportNote:"לוקחים את קו Yamatoji Line לתחנת Kamo Station (~15 דקות) ולאחר מכן שאטל. ההגעה דורשת שאטל שנסגור מראש – כדאי להיצמד לזמנים" },
        { id:"d7-a1", type:"activity", time:"", emoji:"🍵", title:"חוויית התה ב-Obubu Tea Farm", titleEn:"Obubu Tea Farm Wazuka", mapsQuery:"Obubu+Tea+Farm+Wazuka+Japan", description:"צלילה לעולם התה עם המקומיים ששם חיים. סיור, טעימות והסברים על ההבדל בין סנצ'ה למאצ'ה", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d7-a2", type:"activity", time:"", emoji:"🚲", title:"גלגלים על בין השדות", titleEn:"Wazuka Tea Fields Cycling", mapsQuery:"Wazuka+Tea+Plantations+Japan", description:"שוכרים אופניים חשמליים (חובה! יש עליות) בתחנת המידע או דרך החווה. יוצאים לרכיבה עם המפה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d7-a3", type:"activity", time:"", emoji:"📸", title:"Ishitera Tea Plantations", titleEn:"Ishitera Tea Plantations Wazuka", mapsQuery:"Ishitera+Tea+Plantations+Wazuka+Japan", description:"נקודת חובה לצילום – זו התצפית הכי מפורסמת של וואזוקה (השדות שמטפסים לשמיים)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d7-r1", type:"restaurant", time:"", emoji:"🍽", title:"צהריים ב-d:matcha Kyoto Café", titleEn:"d:matcha Kyoto Cafe Wazuka", mapsQuery:"d:matcha+Kyoto+Cafe+Wazuka+Japan", description:"הארוחה הכי אסתטית בטיול – פסטה ירוקה וקינוחים שחבל לאכול מרוב שהם יפים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d7-t2", type:"transport", time:"", emoji:"🚌", title:"חזרה לנארה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Bus 66 + Train", from:"Wazuka", to:"JR Nara", duration:"~45 דקות", transportNote:"מחזירים את האופניים, לוקחים את אוטובוס 66 מתחנת Wazuka חזרה לתחנת Kamo, רכבת מ-Kamo חזרה ל-JR Nara" },
        { id:"d7-a4", type:"activity", time:"", emoji:"🏮", title:"ערב רגוע בנארה העתיקה (Naramachi)", titleEn:"Naramachi Nara", mapsQuery:"Naramachi+Nara+Japan", description:"אחרי יום בכפר חוזרים לנארה לערב רגוע באזור Naramachi. בניגוד לאוסקה הרועשת, כאן האווירה בערב קסומה ושקטה. לכו לאגם Sarusawa Pond בשקיעה/ערב – הפגודה של מקדש Kofukuji משתקפת במים. המקום המושלם לסגור את היום", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d7-r2", type:"restaurant", time:"", emoji:"🍣", title:"ארוחת ערב – Maguro Koya", titleEn:"Maguro Koya Nara", mapsQuery:"Maguro+Koya+Nara+Japan", description:"מסעדה קטנה ופשוטה שמתמחה בטונה (Maguro) ברמה מטורפת. מומלץ לקחת את ה-Otoro (החלק השמן והנימוח)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["ההגעה לוואזוקה דורשת שאטל שנסגור מראש – כדאי להיצמד לזמנים", "Harushika Sake Brewery – מבשלת סאקה מפורסמת בנארה שמציעה טעימות, אם בא לכם דרינק"],
      appendix: []
    },
    {
      id: "day-8", date: "2026-03-24", dayOfWeek: "שלישי", title: "הירושימה", city: "הירושימה", cityEn: "Hiroshima", color: "#FF5722",
      hotel: { name: "Hotel Granvia Hiroshima", mapsQuery: "Hotel+Granvia+Hiroshima+Japan" },
      items: [
        { id:"d8-t1", type:"transport", time:"", emoji:"🚅", title:"שינקנסן להירושימה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Shinkansen Nozomi", from:"Osaka/Kyoto", to:"Hiroshima", duration:"~1:40 שעות", transportNote:"קחו רכבת עד תחנת אוסקה או קיוטו, משם שינקנסן נוזומי (רכבת מהירה) להירושימה" },
        { id:"d8-a1", type:"activity", time:"", emoji:"🏨", title:"צ'ק אין במלון", titleEn:"Hotel Granvia Hiroshima", mapsQuery:"Hotel+Granvia+Hiroshima+Japan", description:"", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d8-a2", type:"activity", time:"", emoji:"🗺", title:"פארק השלום והמוזיאון להנצחת השלום", titleEn:"Hiroshima Peace Memorial Park", mapsQuery:"Hiroshima+Peace+Memorial+Park+Japan", description:"חוויה עוצמתית – המוזיאון שמסביר על הפצצה האטומית", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d8-a3", type:"activity", time:"", emoji:"🏛", title:"כיפת הפצצה האטומית (Genbaku Dome)", titleEn:"Genbaku Dome Hiroshima", mapsQuery:"Genbaku+Dome+Hiroshima+Japan", description:"שריד היסטורי מרשים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d8-a4", type:"activity", time:"", emoji:"🏯", title:"טירת הירושימה", titleEn:"Hiroshima Castle", mapsQuery:"Hiroshima+Castle+Japan", description:"שחזור של טירה יפנית מסורתית עם נוף יפהפה מהקומה העליונה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d8-a5", type:"activity", time:"", emoji:"🛍", title:"רחוב הונדורי", titleEn:"Hondori Street Hiroshima", mapsQuery:"Hondori+Street+Hiroshima+Japan", description:"רחוב קניות תוסס עם מסעדות ובתי קפה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d8-r1", type:"restaurant", time:"", emoji:"🍣", title:"ארוחת ערב – Okonomimura", titleEn:"Okonomimura Hiroshima", mapsQuery:"Okonomimura+Hiroshima+Japan", description:"קומפלקס מסעדות המתמחות באוקונומיאקי – המאכל המקומי של הירושימה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: [
        { id:"d8-x1", type:"activity", time:"", emoji:"💡", title:"גן שוקאין (Shukkeien Garden)", titleEn:"Shukkeien Garden Hiroshima", mapsQuery:"Shukkeien+Garden+Hiroshima+Japan", description:"אם יש זמן לפני החזרה – פארק יפהפה עם גשרים מסורתיים ותחושה פסטורלית", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ]
    },
    {
      id: "day-9", date: "2026-03-25", dayOfWeek: "רביעי", title: "אי איצוקושימה וקיוטו", city: "הירושימה", cityEn: "Hiroshima", color: "#FF5722",
      hotel: { name: "מלון בקיוטו", mapsQuery: "Kyoto+Station+Hotel+Japan" },
      items: [
        { id:"d9-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לאי מיאג'ימה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"JR + Ferry", from:"Hiroshima", to:"Miyajima Island", duration:"~35 דקות", transportNote:"רכבת JR מהירושימה לתחנת Miyajimaguchi (25 דקות) + הפלגה במעבורת (10 דקות)" },
        { id:"d9-a1", type:"activity", time:"", emoji:"⛩", title:"מקדש איצוקושימה ושער הטורי הצף", titleEn:"Itsukushima Shrine Miyajima", mapsQuery:"Itsukushima+Shrine+Miyajima+Japan", description:"מבנה עץ יפיפה שבנוי על המים – שער הטורי הצף האייקוני", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d9-a2", type:"activity", time:"", emoji:"🚠", title:"עלייה ברכבל להר מיסן", titleEn:"Mt Misen Ropeway Miyajima", mapsQuery:"Mt+Misen+Ropeway+Miyajima+Japan", description:"נוף מרהיב של מפרץ הירושימה והאיים סביבו", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d9-r1", type:"restaurant", time:"", emoji:"🍽", title:"צהריים ברחוב אומוטסנדו", titleEn:"Omotesando Street Miyajima", mapsQuery:"Omotesando+Street+Miyajima+Japan", description:"טעימות של חטיפי מייפל, אויסטרים מקומיים ומנות ייחודיות לאזור", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d9-t2", type:"transport", time:"", emoji:"🚆", title:"חזרה להירושימה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Ferry + JR", from:"Miyajima", to:"Hiroshima", duration:"~35 דקות", transportNote:null },
        { id:"d9-t3", type:"transport", time:"", emoji:"🚅", title:"שינקנסן לקיוטו", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Shinkansen Nozomi", from:"Hiroshima", to:"Kyoto", duration:"~שעתיים", transportNote:"רכבת שינקנסן נוזומי מתחנת הירושימה המרכזית לתחנת קיוטו" },
        { id:"d9-a3", type:"activity", time:"", emoji:"🏨", title:"צ'ק אין למלון בקיוטו והתחלת היום בעיר", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: []
    },
    {
      id: "day-10", date: "2026-03-26", dayOfWeek: "חמישי", title: "מרכז קיוטו – שוק נישיקי וטירת ניג'ו", city: "קיוטו", cityEn: "Kyoto", color: "#9C27B0",
      hotel: { name: "מלון בקיוטו", mapsQuery: "Kyoto+Station+Hotel+Japan" },
      items: [
        { id:"d10-r1", type:"restaurant", time:"", emoji:"🍱", title:"שוק נישיקי", titleEn:"Nishiki Market Kyoto", mapsQuery:"Nishiki+Market+Kyoto+Japan", description:"פותחים את היום בטיילת הצבעונית של שוק נישיקי – שוק האוכל הכי שווה בקיוטו. מאכלים יפניים מסורתיים, דוכני דגים, חטיפים מוזרים (אבל טעימים), תה יפני, קינוחים מפתיעים ואפילו סוכריות בצורת דגים. מומלץ לשוטט, לטעום, לעצור פה ושם ולצלם – פשוט חוויה לכל החושים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d10-a1", type:"activity", time:"", emoji:"🛍", title:"רחוב Shinkyogoku", titleEn:"Shinkyogoku Shopping Street Kyoto", mapsQuery:"Shinkyogoku+Shopping+Street+Kyoto+Japan", description:"הרחוב המקורה נמצא צמוד לשוק – מציע קניות: בגדים, מזכרות, צעצועים, חנויות אנימה, גאדג'טים וכל מה שמנצנץ", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d10-a2", type:"activity", time:"", emoji:"🏯", title:"טירת ניג'ו", titleEn:"Nijo Castle Kyoto", mapsQuery:"Nijo+Castle+Kyoto+Japan", description:"אחד המקומות המרשימים בעיר – ארמונות עץ עם ציורי זהב על הדלתות, רצפה שמצייצת כשצועדים עליה (כדי לתפוס מתנקשים!), וגנים מטופחים מסביב. מקום שכולו כוח וסטייל סמוראי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d10-r2", type:"restaurant", time:"", emoji:"🍽", title:"ארוחת ערב בפונטוצ'ו – יקינאקו ב-AJE", titleEn:"AJE Yakiniku Pontocho Kyoto", mapsQuery:"AJE+Pontocho+Kyoto+Japan", description:"המלצה שלי לערב – מבשלים את הבשר בגריל משלכם! אני ממש נהניתי במסעדה הזו – בשר מאוד איכותי במחירים לא יקרים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d10-r3", type:"restaurant", time:"", emoji:"🍶", title:"בר L'Escamoteur", titleEn:"L'Escamoteur Bar Kyoto", mapsQuery:"L'Escamoteur+Bar+Kyoto+Japan", description:"בר אירופאי מטורף עם קוקטיילים מעולים – אפשר להמשיך מ-AJE", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["מה שטוב בקיוטו – שאין את הלחץ של אוסקה או טוקיו. חוויית קניות רגועה והרבה יותר נעימה"],
      appendix: []
    },
    {
      id: "day-11", date: "2026-03-27", dayOfWeek: "שישי", title: "אראשיאמה והמקדש המוזהב", city: "קיוטו", cityEn: "Kyoto", color: "#9C27B0",
      hotel: { name: "מלון בקיוטו", mapsQuery: "Kyoto+Station+Hotel+Japan" },
      items: [
        { id:"d11-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לאראשיאמה", titleEn:"", mapsQuery:null, description:"יוצאים מוקדם מקיוטו לקמאאוקה (JR Sagano או רכבת הנוף Torokko) ויורדים לרציף השייט", fee:null, bookInAdvance:false, line:"JR Sagano / Torokko", from:"Kyoto", to:"Kameoka", duration:"~30 דקות", transportNote:null },
        { id:"d11-a1", type:"activity", time:"", emoji:"🚣", title:"שייט נהר Hozugawa", titleEn:"Hozugawa River Boat Ride", mapsQuery:"Hozugawa+River+Boat+Ride+Arashiyama+Japan", description:"שעתיים של נהר, הרים ויער – סירה מסורתית עם זרימות קטנות. השייט מסתיים באראשיאמה ישירות ליד גשר טוגצוקיו", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a2", type:"activity", time:"", emoji:"⛩", title:"מקדש טנריו-ג'י", titleEn:"Tenryu-ji Temple Arashiyama", mapsQuery:"Tenryu-ji+Temple+Arashiyama+Kyoto+Japan", description:"מקדש זן עתיק ומרהיב, מוקף בגנים יפניים שלווים עם בריכת דגים ונוף להרים. אחד המקדשים המרשימים באזור", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a3", type:"activity", time:"", emoji:"🏡", title:"גני אוקוצ'י סאנסו", titleEn:"Okochi Sanso Garden Arashiyama", mapsQuery:"Okochi+Sanso+Garden+Arashiyama+Kyoto+Japan", description:"סיור בגנים השקטים עם תצפית מדהימה על קיוטו (כחצי שעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a4", type:"activity", time:"", emoji:"🎋", title:"יער הבמבוקים של אראשיאמה", titleEn:"Arashiyama Bamboo Forest", mapsQuery:"Arashiyama+Bamboo+Forest+Kyoto+Japan", description:"שבילים מוקפים בגזעים ירוקים שמתנשאים לגובה עצום – תחושה של כניסה לעולם אחר. הולכים לאט ביער, נותנים לאור להשתבר דרך העלים ולצלילים של הרוח לעשות את שלהם. פשוט וואו (כשעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a5", type:"activity", time:"", emoji:"📸", title:"תצפית Arashiyama Park", titleEn:"Arashiyama Park Viewpoint", mapsQuery:"Arashiyama+Park+Viewpoint+Kyoto+Japan", description:"עלייה קטנה ונעימה (לא מאתגרת) שבסופה מגיעים למרפסת עץ עם נוף פנורמי משוגע על נהר ההוזו וההרים שמסביב (כחצי שעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a6", type:"activity", time:"", emoji:"🐵", title:"פארק הקופים של אראשיאמה", titleEn:"Monkey Park Iwatayama Arashiyama", mapsQuery:"Monkey+Park+Iwatayama+Arashiyama+Kyoto+Japan", description:"עלייה של 25 דקות לפסגה עם קופים חופשיים ונוף פנורמי. אפשר להאכיל את הקופים – חוויה שאין לה שני ביפן לדעתי (כשעתיים)", fee:{amount:800,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-r1", type:"restaurant", time:"", emoji:"🍽", title:"ארוחת צהריים ומעבר דרך הגשר", titleEn:"Togetsukyō Bridge Arashiyama", mapsQuery:"Togetsukyo+Bridge+Arashiyama+Kyoto+Japan", description:"ארוחת צהריים באזור ומעבר דרך גשר טוגצוקיו", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a7", type:"activity", time:"", emoji:"⛩", title:"טקס תה וקימונו", titleEn:"Tea Ceremony Kyoto", mapsQuery:"Tea+Ceremony+Kyoto+Japan", description:"לחוות את המסורת היפנית עם קימונו וטקס תה מסורתי עם מאסטרית באווירה רגועה ומסקרנת", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a8", type:"activity", time:"", emoji:"⛩", title:"מקדש קינקאקו-ג'י (הפביליון המוזהב)", titleEn:"Kinkaku-ji Temple Kyoto", mapsQuery:"Kinkaku-ji+Temple+Kyoto+Japan", description:"ביקור בפביליון המוזהב המרהיב – אחד האתרים המפורסמים ביפן. מקדש זן ששלוש הקומות שלו מצופות בזהב טהור, ומשתקפות על פני אגם שקט עם עצים מסביב. נבנה במאה ה-14 כווילה של שוגון עשיר, נשרף ב-1950 ושוחזר בדיוק מופתי (כשעה)", fee:{amount:500,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d11-a9", type:"activity", time:"", emoji:"🏮", title:"טיול לאורך נהר קאמוגאווה", titleEn:"Kamogawa River Kyoto", mapsQuery:"Kamogawa+River+Kyoto+Japan", description:"סיום היום עם טיול לאורך נהר קאמוגאווה – חוויה קסומה בלילה, עם תאורת רחוב יפה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["ניתן לשכור סירה ולשוט בנהר ליד גשר טוגצוקיו (כשעה)"],
      appendix: []
    },
    {
      id: "day-12", date: "2026-03-28", dayOfWeek: "שבת", title: "פושימי אינארי, קיומיזו-דרה וגיון", city: "קיוטו", cityEn: "Kyoto", color: "#9C27B0",
      hotel: { name: "מלון בקיוטו", mapsQuery: "Kyoto+Station+Hotel+Japan" },
      items: [
        { id:"d12-a1", type:"activity", time:"", emoji:"⛩", title:"מדיטציית זן במקדש ריוסוקואין", titleEn:"Ryosokuin Zen Temple Kyoto", mapsQuery:"Ryosokuin+Zen+Temple+Kyoto+Japan", description:"מקדש ריוסוקואין השוכן במתחם קנז'י שבגיון, מציע חוויית מדיטציית זן אותנטית עם נזיר מקומי, באווירה שקטה ומוקפדת של גן יפני מסורתי", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-a2", type:"activity", time:"", emoji:"⛩", title:"מקדש פושימי אינארי", titleEn:"Fushimi Inari Taisha Kyoto", mapsQuery:"Fushimi+Inari+Taisha+Kyoto+Japan", description:"אחד האתרים האייקוניים של קיוטו – סיור בשערי הטורי הכתומים, הליכה במסלולים הקסומים ועלייה לתצפית מרשימה על קיוטו. הליכה בשביל הטוריאי – מסלול יפהפה בין השערים עד נקודת תצפית (כשעתיים תלוי בכם)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לקיומיזו-דרה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Keihan Main Line", from:"Fushimi Inari", to:"Kiyomizu-dera area", duration:"~20 דקות", transportNote:null },
        { id:"d12-a3", type:"activity", time:"", emoji:"⛩", title:"מקדש קיומיזו-דרה", titleEn:"Kiyomizu-dera Temple Kyoto", mapsQuery:"Kiyomizu-dera+Temple+Kyoto+Japan", description:"סיור באחד המקדשים היפים של קיוטו, עם תצפית מרהיבה על העיר (¥500)", fee:{amount:500,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-a4", type:"activity", time:"", emoji:"🚶‍♂️", title:"מפל Otowanotaki", titleEn:"Otowanotaki Waterfall Kiyomizu", mapsQuery:"Otowanotaki+Waterfall+Kiyomizu+Kyoto+Japan", description:"הליכה למפל עם מי מעיין קדושים – שותים מהם לבריאות ולמזל", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-a5", type:"activity", time:"", emoji:"🚶‍♂️", title:"שדרת נינזאקה", titleEn:"Ninenzaka Kyoto", mapsQuery:"Ninenzaka+Kyoto+Japan", description:"הליכה ברחוב מסורתי עם חנויות מיוחדות, תה יפני וקינוחים מסורתיים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-a6", type:"activity", time:"", emoji:"🍵", title:"עצירה בבית תה מסורתי", titleEn:"Traditional Tea House Kyoto", mapsQuery:"Ninenzaka+Tea+House+Kyoto+Japan", description:"חוויית תה ירוק אותנטית עם ממתק ואווירה מסורתית", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-r1", type:"restaurant", time:"", emoji:"🍽", title:"ארוחת צהריים", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-a7", type:"activity", time:"", emoji:"📸", title:"תצפית על פגודה יאסאקה", titleEn:"Yasaka Pagoda Kyoto", mapsQuery:"Yasaka+Pagoda+Kyoto+Japan", description:"אחת מהתמונות האייקוניות של קיוטו (¥400)", fee:{amount:400,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-a8", type:"activity", time:"", emoji:"⛩", title:"מקדש קודאי-ג'י", titleEn:"Kodaiji Temple Kyoto", mapsQuery:"Kodaiji+Temple+Kyoto+Japan", description:"מקדש זן עתיק עם גנים יפניים מרהיבים וגשר עץ ייחודי. אם תגיעו בערב יש תערוכה אור קולית על המקדש – לא לפספס! (¥600)", fee:{amount:600,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-a9", type:"activity", time:"", emoji:"🏮", title:"סיור ערב באזור גיון", titleEn:"Gion District Kyoto", mapsQuery:"Gion+District+Kyoto+Japan", description:"הרובע ההיסטורי – המלצה שלי להתחיל במקדש יאסקה המואר בערב ופארק מריומה ורק לאחר מכן להיכנס לתוך הרובע ולגיון עצמה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d12-r2", type:"restaurant", time:"", emoji:"🍶", title:"בילוי בפונטוצ'ו", titleEn:"Pontocho Kyoto", mapsQuery:"Pontocho+Kyoto+Japan", description:"אופציונלי: סמטת הלילה של קיוטו עם מסעדות וברים לאורך הנהר", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: []
    },
    {
      id: "day-13", date: "2026-03-29", dayOfWeek: "ראשון", title: "שביל הפילוסופים ותיאטרון גיר", city: "קיוטו", cityEn: "Kyoto", color: "#9C27B0",
      hotel: { name: "מלון בקיוטו", mapsQuery: "Kyoto+Station+Hotel+Japan" },
      items: [
        { id:"d13-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה למקדש הכסף", titleEn:"", mapsQuery:null, description:"נסיעה בקו Keihan או באוטובוס לאזור צפון מזרח העיר", fee:null, bookInAdvance:false, line:"Keihan / Bus", from:"Kyoto center", to:"Ginkaku-ji area", duration:"~25 דקות", transportNote:null },
        { id:"d13-a1", type:"activity", time:"", emoji:"🚶‍♂️", title:"שביל הפילוסופים", titleEn:"Philosopher's Path Kyoto", mapsQuery:"Philosopher's+Path+Kyoto+Japan", description:"הליכה רגועה ופסטורלית לאורך התעלה, מוצל על ידי עצי הדובדבן, עם חנויות קטנות, בוטיקים ובתי קפה ציוריים פזורים שלאורכו (כחצי שעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d13-a2", type:"activity", time:"", emoji:"⛩", title:"מקדש הכסף (גינקאקו-ג'י)", titleEn:"Ginkaku-ji Silver Pavilion Kyoto", mapsQuery:"Ginkaku-ji+Temple+Kyoto+Japan", description:"למרות שמו, אינו מצופה כסף, אך הוא מוקף בגני זן מטופחים ומרשימים במיוחד הכוללים את 'ים החול הכסוף' (¥500)", fee:{amount:500,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d13-a3", type:"activity", time:"", emoji:"🎨", title:"אזור אוקאזאקי", titleEn:"Okazaki District Kyoto", mapsQuery:"Okazaki+District+Kyoto+Japan", description:"צעידה דרומה מהשביל לשכונה המשלבת אמנות, מסורת ואווירה מודרנית", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d13-a4", type:"activity", time:"", emoji:"🏺", title:"מרכז יד מלאכת קיוטו", titleEn:"Kyoto Handicraft Center", mapsQuery:"Kyoto+Handicraft+Center+Japan", description:"מתחם המציג אומנות מקומית יד בעבודת – קרמיקה, טקסטיל קיוטואי, כלי תה, בובות מסורתיות וחרבות סמוראים (קטאנה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d13-a5", type:"activity", time:"", emoji:"🖼", title:"מוזיאון האמנות של קיוטו KYOCERA", titleEn:"Kyoto City KYOCERA Museum of Art", mapsQuery:"Kyoto+City+KYOCERA+Museum+of+Art+Japan", description:"מוזיאון מוביל המציג אוסף יצירות יפניות מסורתיות לצד תערוכות עכשוויות מתחלפות (¥750)", fee:{amount:750,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d13-a6", type:"activity", time:"", emoji:"🗼", title:"תצפית ממגדל קיוטו", titleEn:"Kyoto Tower", mapsQuery:"Kyoto+Tower+Japan", description:"תצפית פנורמית מדהימה מגובה 131 מטרים. אפשר גם לעלות לתצפית חינמית בקומה ה-12 של תחנת הרכבת (¥900 למגדל)", fee:{amount:900,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d13-r1", type:"restaurant", time:"", emoji:"🍽", title:"מנוחה וקפה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d13-a7", type:"activity", time:"", emoji:"🎭", title:"מופע תיאטרון גיר", titleEn:"Gear Theatre Kyoto", mapsQuery:"Gear+Theatre+Kyoto+Japan", description:"מסיימים את היום במופע המדובר של קיוטו – חוויה ויזואלית לא-ורבלית (מתאים לכולם) המשלבת אומנות דיגיטלית, קסמים, אקרובטיקה, מייצגי אור ומוזיקה קצבית. שילוב מדהים של טכנולוגיה ותיאטרון (~₪350 לזוג)", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: []
    },
    {
      id: "day-14", date: "2026-03-30", dayOfWeek: "שני", title: "יום טיול בנגויה – טירות, מכוניות והקסם של גיבלי", city: "נגויה", cityEn: "Nagoya", color: "#FF9800",
      hotel: { name: "The Strings Hotel Nagoya", mapsQuery: "The+Strings+Hotel+Nagoya+Japan" },
      items: [
        { id:"d14-t1", type:"transport", time:"", emoji:"🚅", title:"נסיעה לנגויה", titleEn:"", mapsQuery:null, description:"צ'ק אאוט מהמלון בקיוטו, הפקדת טרולי בקבלה ויציאה לדרך", fee:null, bookInAdvance:false, line:"JR Shinkansen", from:"Kyoto", to:"Nagoya", duration:"~35 דקות", transportNote:"ברכבת המהירה של JR מתחנה מרכזית" },
        { id:"d14-a1", type:"activity", time:"", emoji:"🏯", title:"טירת נגויה", titleEn:"Nagoya Castle", mapsQuery:"Nagoya+Castle+Japan", description:"מתחילים את היום באחד הסמלים החשובים של יפן. ישנו את שחזור ארמון הונמארו המפואר עם ציורי הקיר המוזהבים, ואת פסלי הדולפינים המוזהבים שבראש הטירה. מומלץ להגיע מוקדם עקב עומס (שעה-שעה וציוח)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d14-a2", type:"activity", time:"", emoji:"🚗", title:"מוזיאון הרכב של טויוטה", titleEn:"Toyota Automobile Museum", mapsQuery:"Toyota+Automobile+Museum+Nagakute+Japan", description:"נסיעה לכיוון מזרח העיר (אזור Nagakute) למוזיאון המוקדש להיסטוריה של הרכב העולמי. בפנים אוסף מדהים של רכבים קלאסיים מכל העולם, מהמכוניות הראשונות בהיסטוריה ועד רכבי יוקרה מודרניים. כולל מסעדה עם קארי יפני בעל שם ברשתות החברתיות", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d14-a3", type:"activity", time:"", emoji:"🎬", title:"פארק גיבלי", titleEn:"Ghibli Park Nagakute", mapsQuery:"Ghibli+Park+Nagakute+Japan", description:"נמצא במרחק נסיעה קצרה בקו ה-Linimo ממוזיאון הרכב (תחנת Ai-Chikyuhaku Kinen Koen). בניגוד לדיסנילנד, זהו פארק שמשתלב בנוף בלי מתקנים, עם מתחמים כמו 'המחסן הגדול של גיבלי', 'יער דונדוקו' ועוד", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:"רכבת ה-Linimo (רכבת מגנטית מרחפת) היא אטרקציה בפני עצמה ומחברת בין מוזיאון הרכב לפארק גיבלי" },
        { id:"d14-a4", type:"activity", time:"", emoji:"🚀", title:"Oasis 21 – ספינת החלל", titleEn:"Oasis 21 Nagoya", mapsQuery:"Oasis+21+Nagoya+Japan", description:"בערב, חזרה למרכז העיר לאזור הקניות והבילויים המרכזי. מבנה עתידני מרהיב שנראה כמו ספינת חלל עשויה זכוכית ומים. ניתן לעלות לגג להליכה מסביב לבריכת המים עם תצפית מדהימה על מגדל הטלוויזיה של נגויה (Mirai Tower) המואר בלילה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["שימו לב שיש שני מוזיאונים לטויוטה בנגויה. המסלול הזה כולל את Toyota Automobile Museum (בנגקוטה, ליד גיבלי). המוזיאון השני (Commemorative Museum) נמצא במרכז העיר ועוסק יותר בטכנולוגיה וטקסטיל", "רכבת ה-Linimo (מגנטית מרחפת) היא אטרקציה בפני עצמה"],
      appendix: []
    },
    {
      id: "day-15", date: "2026-03-31", dayOfWeek: "שלישי", title: "שינגוקו ושין-אוקובו", city: "טוקיו", cityEn: "Tokyo", color: "#E91E63",
      hotel: { name: "מלון בטוקיו", mapsQuery: "Shinjuku+Hotel+Tokyo+Japan" },
      items: [
        { id:"d15-t1", type:"transport", time:"10:00", emoji:"🚅", title:"נסיעה לטוקיו", titleEn:"", mapsQuery:null, description:"צ'ק אאוט מהמלון בנגויה, השארת טרולי במלון בקבלה ויציאה ברכבת", fee:null, bookInAdvance:false, line:"Shinkansen", from:"Nagoya", to:"Shinjuku Station", duration:"~1:40 שעות", transportNote:"ברכבת מתחנה מרכזית עד תחנת שינגוקו. צ'ק אין במלון, השארת טרולי, מנוחה קצרה ויציאה" },
        { id:"d15-a1", type:"activity", time:"", emoji:"🇰🇷", title:"שכונה קוריאנית שין-אוקובו", titleEn:"Shin-Okubo Korean Town Tokyo", mapsQuery:"Shin-Okubo+Korean+Town+Tokyo+Japan", description:"תחנה אחת בלבד מנשינגוקו בקו Yamanote – ואתם נוחתים בקוריאה הקטנה של טוקיו. שלטים בקוריאנית, חנויות מתפוצצות בצבעים – קוסמטיקה קוריאנית, תחפושות, גאצ'ות, פוסטרים וסטייל. טעימות של טוסט קוריאני, קורנדוגים נמסים, גונג'גונג ובאנים ברוטב", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d15-a2", type:"activity", time:"", emoji:"📸", title:"Photo Booth וחוויית Hanbok", titleEn:"Photo Booth Shin-Okubo", mapsQuery:"Shin-Okubo+Photo+Booth+Tokyo+Japan", description:"נכנסים ל-Photo Booth עם מסגרת מוגזמת ומקבלים תמונה מצחיקה למזכרת. אפשר גם לבחור בגד Hanbok (כובע קוריאני מסורתי) יפהפה, להתלבש, להצטלם על רקע פרחוני ולחוות רגע של מלכות בסטייל של סדרה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d15-a3", type:"activity", time:"", emoji:"🌳", title:"פארק שינגוקו גיואן", titleEn:"Shinjuku Gyoen National Garden", mapsQuery:"Shinjuku+Gyoen+National+Garden+Tokyo+Japan", description:"חוזרים לשינגוקו – גנים יפניים, בריכות, דגים ונוף ירוק באמצע העיר. מומלץ להביא איתכם בנטו מהשכונה הקוריאנית לפיקניק (כניסה ¥500)", fee:{amount:500,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d15-a4", type:"activity", time:"", emoji:"🛍", title:"שופינג בקניוני שינגוקו", titleEn:"Shinjuku Shopping Tokyo", mapsQuery:"Shinjuku+Shopping+Tokyo+Japan", description:"Lumine / NEWoMan – אופנה, אוכל, מותגים. Don Quijote – חנות ענק עם כל מה שצריכים ולא ידעתם. Bic Camera – גאדג'טים, מוצרי חשמל, מצלמות, שעונים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d15-a5", type:"activity", time:"", emoji:"🗼", title:"תצפית מבניין עיריית טוקיו", titleEn:"Tokyo Metropolitan Government Building", mapsQuery:"Tokyo+Metropolitan+Government+Building+Japan", description:"לקראת הערב – תצפית חינמית מגובה 202 מטר עם נוף מטורף על כל טוקיו. בערב מוקרן מופע אור קולי על הבניין כל חצי שעה! (להקדיש כשעה וחצי לתצפית והמופע)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d15-a6", type:"activity", time:"", emoji:"🏮", title:"Kabukicho + Golden Gai", titleEn:"Kabukicho Golden Gai Shinjuku", mapsQuery:"Kabukicho+Golden+Gai+Shinjuku+Tokyo+Japan", description:"שינגוקו בלילה – שלטי ניאון עצומים, מוזיקה, גודזילה מעל המלון, משחקי ארקייד עם קפיצה ל-Don Quijote (הסניף פתוח 24/7! נסו להגיע לקומה למעלה). שיטוט בסמטאות Golden Gai – ברים קטנטנים, וויסקי, ג'אז, סרטים, מקום ל-6 אנשים בלבד ותרגישו יפן של פעם", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d15-a7", type:"activity", time:"", emoji:"🎤", title:"קריוקי!", titleEn:"Karaoke Shinjuku", mapsQuery:"Karaoke+Shinjuku+Tokyo+Japan", description:"אם עוד יש כוח – שינגוקו מלאה במתחמי קריוקי פרטיים (כמו Big Echo או Karaoke-kan). חדר עם מסך, מיקרופון ואנרגיה!", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: []
    },
    {
      id: "day-16", date: "2026-04-01", dayOfWeek: "רביעי", title: "אסאקוסה וסומידה", city: "טוקיו", cityEn: "Tokyo", color: "#E91E63",
      hotel: { name: "מלון בטוקיו", mapsQuery: "Shinjuku+Hotel+Tokyo+Japan" },
      items: [
        { id:"d16-a1", type:"activity", time:"", emoji:"🗼", title:"תצפית ממרכז התיירים של אסאקוסה", titleEn:"Asakusa Culture Tourist Information Center", mapsQuery:"Asakusa+Culture+Tourist+Information+Center+Tokyo+Japan", description:"מבנה בן שמונה קומות מול שער הקמינארימון. בקומה העליונה תצפית עם נוף על רובע אסאקוסה והאזור ההיסטורי. בכל קומה אחרת תגלו איזור של תערוכה קטנה מאומנות ועד משחקי ילדות יפניים (כחצי שעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d16-a2", type:"activity", time:"", emoji:"🛍", title:"שיטוט ברחוב נקמיסה", titleEn:"Nakamise-dori Street Asakusa", mapsQuery:"Nakamise-dori+Street+Asakusa+Tokyo+Japan", description:"אחד מרחובות הקניות העתיקים בטוקיו – משתרע עד מקדש סנסו-ג'י ומלא בכ-90 חנויות ודוכנים המציעים מזכרות, חטיפים יפניים מסורתיים ומוצרים מקומיים. אם רוצים לנסות מאכל מיוחד – נסו את הדאנגו, כופתאות בצורת כדור מאורז דביק עם רוטב מעל (שעה וחצי עם המקדש)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d16-a3", type:"activity", time:"", emoji:"⛩", title:"מקדש סנסו-ג'י", titleEn:"Sensō-ji Temple Asakusa", mapsQuery:"Senso-ji+Temple+Asakusa+Tokyo+Japan", description:"בסוף רחוב נקמיסה – המקדש הבודהיסטי העתיק ביותר בטוקיו, שנבנה במאה ה-7. מפורסם בזכות שער קמינארימון האייקוני ופנס הנייר האדום הענק התלוי בו", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d16-r1", type:"restaurant", time:"", emoji:"🍽", title:"ארוחת צהריים באזור אסאקוסה", titleEn:"Asakusa Restaurants", mapsQuery:"Asakusa+Restaurants+Tokyo+Japan", description:"", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d16-a4", type:"activity", time:"", emoji:"🛍", title:"שופינג במתחם ROX אסאקוסה", titleEn:"ROX Asakusa Shopping", mapsQuery:"ROX+Asakusa+Tokyo+Japan", description:"קומפלקס עם כמה בניינים – חנויות אופנה, אביזרים ומוצרים לבית. המלצה שלי – DAISO בקומה העליונה (כ-45 דקות)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d16-a5", type:"activity", time:"", emoji:"🔪", title:"רחוב כלי המטבח קאפאבשי", titleEn:"Kappabashi Kitchen Street Tokyo", mapsQuery:"Kappabashi+Kitchen+Street+Tokyo+Japan", description:"כ-10 דקות הליכה מאסאקוסה. רחוב שאורכו כמעט קילומטר, מוקדש לחנויות המתמחות בכלי מטבח – סכינים יפניות, כלי אוכל, ודגמי אוכל מפלסטיק המשמשים לתצוגה במסעדות. גן עדן לחובבי בישול! (כשעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d16-a6", type:"activity", time:"", emoji:"🎭", title:"שיטוט ברחוב Hoppy Dori", titleEn:"Hoppy Dori Asakusa", mapsQuery:"Hoppy+Dori+Asakusa+Tokyo+Japan", description:"לקראת ערב – רחוב מפורסם בזכות האיזקיות (פאבים יפניים) המסורתיות שבו, המציעות מגוון מנות קטנות ומשקאות. האווירה תוססת במיוחד בשעות הערב – מקום מצוין לחוות את חיי הלילה המקומיים, לטעום מנות יפניות אותנטיות וליהנות מבירה או סאקה (כשעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["שימו לב יום רגוע יחסית, שכן מה חם נורא – אמליץ להתמקם באיזורים סגורים וממוזגים יותר"],
      appendix: [
        { id:"d16-x1", type:"activity", time:"", emoji:"🤼‍♂️", title:"מועדון הסומו Asakusa SUMO Club", titleEn:"Asakusa SUMO Club", mapsQuery:"Asakusa+SUMO+Club+Tokyo+Japan", description:"מסעדה ייחודית שבה ניתן לצפות במופעי סומו בזמן ארוחה. מושבים מסביב לזירה, כולל ארוחה ושתייה. המופע: שעה וחצי עם הסברים באנגלית על חוקי הסומו ואפילו להשתתף ו'להילחם' (מ-¥5000)", fee:{amount:5000,currency:"yen",perPerson:true}, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d16-x2", type:"activity", time:"", emoji:"🎡", title:"פארק השעשועים Hanayashiki", titleEn:"Hanayashiki Amusement Park Asakusa", mapsQuery:"Hanayashiki+Amusement+Park+Asakusa+Tokyo+Japan", description:"נפתח בשנת 1853 – פארק השעשועים העתיק ביותר ביפן. האווירה רטרו ומלאה קסם אבוד – לא אקסטרימי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ]
    },
    {
      id: "day-17", date: "2026-04-02", dayOfWeek: "חמישי", title: "יאנאקה, אואנו ואקיהברה", city: "טוקיו", cityEn: "Tokyo", color: "#E91E63",
      hotel: { name: "מלון בטוקיו", mapsQuery: "Shinjuku+Hotel+Tokyo+Japan" },
      items: [
        { id:"d17-a1", type:"activity", time:"", emoji:"🌿", title:"בוקר ביאנאקה", titleEn:"Yanaka District Tokyo", mapsQuery:"Yanaka+District+Tokyo+Japan", description:"אחד האזורים האותנטיים והקסומים ביותר בטוקיו – לא השכונה הכי מתוירת, וזה מה שיפה בה. רובע ששמר על האופי המסורתי שלו – סמטאות צרות, מקדשים קטנים, בתים ישנים ואווירה נינוחה שמזכירה את טוקיו של פעם", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-a2", type:"activity", time:"", emoji:"🛍", title:"רחוב יאנאקה גינזה", titleEn:"Yanaka Ginza Shopping Street", mapsQuery:"Yanaka+Ginza+Tokyo+Japan", description:"רחוב קניות קטן שמלא בדוכנים חמודים – מאפים יפניים, מזכרות, חנויות עתיקות ואפילו חנויות עם חפצים יד בעבודת במחירים סבירים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-a3", type:"activity", time:"", emoji:"🌳", title:"פארק אואנו", titleEn:"Ueno Park Tokyo", mapsQuery:"Ueno+Park+Tokyo+Japan", description:"אחד הפארקים היפים וההיסטוריים ביותר בטוקיו, עם שבילים ירוקים, מקדשים עתיקים ומוזיאונים ברמה עולמית. הבוקר מתחיל בשיטוט בין העצים והשבילים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-a4", type:"activity", time:"", emoji:"🏞", title:"אגם שינובאזו", titleEn:"Shinobazu Pond Ueno", mapsQuery:"Shinobazu+Pond+Ueno+Tokyo+Japan", description:"נוף פסטורלי עם סירות פדלים ומקדש קטן על אי במרכז האגם", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-a5", type:"activity", time:"", emoji:"⛩", title:"מקדש Ueno Toshogu", titleEn:"Ueno Toshogu Shrine", mapsQuery:"Ueno+Toshogu+Shrine+Tokyo+Japan", description:"מקדש שינטו מוזהב עם היסטוריה של מאות שנים, מוקף בגן פנסים יפני", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-a6", type:"activity", time:"", emoji:"🛍", title:"שוק אומייקו", titleEn:"Ameyoko Shopping Street Ueno", mapsQuery:"Ameyoko+Shopping+Street+Ueno+Tokyo+Japan", description:"שוק ססגוני שבעבר היה שוק שחור והיום הוא אחד מהאזורים הכיפיים ביותר לקניות ואוכל רחוב יפני. מזכיר את שוק הכרמל בת'א – הכל כאן יש, מטעימות אוכל רחוב יפני ועד קניות במחירים מעולים – בגדים, תיקים, נעליים, שוקולד וחטיפים יפניים מיוחדים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה לאקיהברה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"JR Yamanote", from:"Ueno", to:"Akihabara", duration:"~5 דקות", transportNote:null },
        { id:"d17-a7", type:"activity", time:"", emoji:"🎮", title:"אקיהברה – גן עדן לגיימרים ואוהבי אנימה", titleEn:"Akihabara Tokyo", mapsQuery:"Akihabara+Tokyo+Japan", description:"מרכז הטכנולוגיה, הגיימינג, האנימה והמנגה של טוקיו. מחנויות אלקטרוניקה ענקיות כמו Yodobashi Camera ו-Bic Camera, דרך חנויות מנגה ואנימה כמו Mandarake עם פריטי אספנות, ועד Super Potato – חנות רטרו גיימינג עם מכונות משחקים קלאסיות בקומה העליונה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-a8", type:"activity", time:"", emoji:"🕹", title:"ארקיידים מטורפים", titleEn:"Sega Akihabara Arcade", mapsQuery:"Sega+Akihabara+Tokyo+Japan", description:"Sega Akihabara ו-Taito Station – משחקי מכונות ומירוצים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-r1", type:"restaurant", time:"", emoji:"☕", title:"Maid Café", titleEn:"Maid Cafe Akihabara", mapsQuery:"Maid+Cafe+Akihabara+Tokyo+Japan", description:"עצירה לקפה מיוחד – מקום שבו המלצריות מחופשות לדמויות אנימה 'משרתות' ויוצרות חוויית שירות משעשעת וחמודה במיוחד", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d17-a9", type:"activity", time:"", emoji:"🏎", title:"קארטינג באקיהברה", titleEn:"Go Karting Akihabara Tokyo", mapsQuery:"Go+Karting+Akihabara+Tokyo+Japan", description:"מסיימים את היום באחת החוויות הייחודיות ביותר בטוקיו – מתלבשים כמו דמויות אנימה או מריו קארט ומקבלים קארט אמיתי לנסוע ברחובות של אקיהברה, בין כל האורות, המסכים הענקיים והחיים המטורפים של השכונה (לסגור מראש)", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: []
    },
    {
      id: "day-18", date: "2026-04-03", dayOfWeek: "שישי", title: "צוקיג'י, טימלאבס וגינזה", city: "טוקיו", cityEn: "Tokyo", color: "#E91E63",
      hotel: { name: "מלון בטוקיו", mapsQuery: "Tokyo+Hotel+Japan" },
      items: [
        { id:"d18-a1", type:"activity", time:"", emoji:"🐟", title:"שוק צוקיג'י החיצוני", titleEn:"Tsukiji Outer Market Tokyo", mapsQuery:"Tsukiji+Outer+Market+Tokyo+Japan", description:"סיור (אופציה למודרך) בשוק הדגים המפורסם – חוויית אוכל רחוב יפני וסושי טרי מהטובים בעולם. המון דברים טעימים, אני מציע לא לפספס אוניגירי סלמון עם ביצי דגים (שעה וחצי)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d18-t1", type:"transport", time:"", emoji:"🚆", title:"נסיעה ל-TeamLab", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Metro", from:"Tsukiji", to:"TeamLab Planets", duration:"~15 דקות", transportNote:null },
        { id:"d18-a2", type:"activity", time:"", emoji:"🎨", title:"TeamLab Planets", titleEn:"TeamLab Planets Tokyo", mapsQuery:"TeamLab+Planets+Tokyo+Japan", description:"חוויית אומנות אינטראקטיבית ומדהימה עם מיצגים דיגיטליים מתקדמים. להקדיש שעה ורבע לפחות ולא לפספס את המיצגים הנוספים (שעה וחצי עד שעתיים)", fee:null, bookInAdvance:true, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d18-t2", type:"transport", time:"", emoji:"🚆", title:"נסיעה לגינזה", titleEn:"", mapsQuery:null, description:"", fee:null, bookInAdvance:false, line:"Metro", from:"TeamLab Planets", to:"Ginza", duration:"~15 דקות", transportNote:null },
        { id:"d18-a3", type:"activity", time:"", emoji:"🏙", title:"שיטוט ברובע היוקרתי גינזה", titleEn:"Ginza District Tokyo", mapsQuery:"Ginza+District+Tokyo+Japan", description:"חוויית קניות ושופינג במתחמי היוקרה – חנויות מותגים בינלאומיים יוקרתיים ומותגים יפניים ייחודיים. שווה לבדוק את חנות הדגל של יוניקלו (12 קומות), חנות הכתיבה הענקית Ito-ya, וחנות הכלבו MUJI שמוכרת מוצרים בעיצוב פשוט ומחירים מעולים. לפחות שעתיים-שלוש", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d18-a4", type:"activity", time:"", emoji:"🏬", title:"כלבו מיצוקושי", titleEn:"Mitsukoshi Ginza", mapsQuery:"Mitsukoshi+Ginza+Tokyo+Japan", description:"אחד מסמלי העיר – להגיע לקומה 2- למבחר גדול של קינוחים יפנים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d18-a5", type:"activity", time:"", emoji:"🎮", title:"אולם התצוגה של סוני", titleEn:"Sony Showroom Ginza", mapsQuery:"Sony+Showroom+Ginza+Tokyo+Japan", description:"מקום לראות, לנסות ולהתנסות בטכנולוגיות הכי חדשות של סוני – מצלמות, קונסולות, רובוטים, טכנולוגיה חדשנית. מעוצב מודרני ואינסטגרמי ממש", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["מעבר מזוודות למלון אחר בטוקיו"],
      appendix: []
    },
    {
      id: "day-19", date: "2026-04-04", dayOfWeek: "שבת", title: "פוג'י והאגמים – יום ראשון", city: "פוג'י", cityEn: "Fuji", color: "#2196F3",
      hotel: { name: "RAKAYUYU ריוקאן", mapsQuery: "RAKAYUYU+Kawaguchiko+Japan" },
      items: [
        { id:"d19-t1", type:"transport", time:"10:00", emoji:"🚅", title:"נסיעה לאזור פוג'י", titleEn:"", mapsQuery:null, description:"צ'ק אאוט מהמלון בטוקיו, נסיעה ברכבת מתחנה מרכזית לתחנת MISHIMA", fee:null, bookInAdvance:false, line:"Shinkansen + Bus", from:"Tokyo Station", to:"Kawaguchiko", duration:"~2 שעות", transportNote:null },
        { id:"d19-a1", type:"activity", time:"", emoji:"🚠", title:"תצפית מרכבל קצ'י-קצ'י", titleEn:"Kachi Kachi Ropeway Kawaguchiko", mapsQuery:"Kachi+Kachi+Ropeway+Kawaguchiko+Japan", description:"עולים ברכבל לפסגת הר טנג'ו שמעל אגם קוואגוצ'יקו – תצפית מהממת על הר פוג'י והאגם מלמעלה. שביל הליכה קצר, אוויר הרים נקי ואגדה יפנית שמוצגת נחמד. העלייה נוחה ולא דורשת טיפוס רגלי (סה\"כ כשעה כולל העלייה, התצפית והירידה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d19-a2", type:"activity", time:"", emoji:"🌸", title:"פארק אושי", titleEn:"Oishi Park Kawaguchiko", mapsQuery:"Oishi+Park+Kawaguchiko+Japan", description:"אחד המקומות הכי יפים, רגועים ומצולמים באגם קוואגוצ'יקו. שביל מטופח לאורך קו המים עם גינות פרחים ונוף להר הפוגי (כ-45 דקות)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d19-a3", type:"activity", time:"", emoji:"♨", title:"ערב בריוקאן עם אונסן", titleEn:"RAKAYUYU Ryokan Kawaguchiko", mapsQuery:"RAKAYUYU+Kawaguchiko+Japan", description:"נוסעים בערב חזרה למלון הריוקאן המסורתי הממוקם על שפת האגם. המלון משלב בין אווירה יפנית אותנטית לנוחות, עם נוף שהוא חוויה בפני עצמה. יש גם אונסן במלון", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["אני ממליץ על החוויה של אונסן פרטי – בגדר חובה"],
      appendix: [
        { id:"d19-x1", type:"activity", time:"", emoji:"🏡", title:"מוזיאון פתוח Hannoki Bayashi", titleEn:"Hannoki Bayashi Shiryokan Oshino Hakkai", mapsQuery:"Hannoki+Bayashi+Shiryokan+Oshino+Hakkai+Japan", description:"פנינה תרבותית בלב כפר המעיינות אושינו האקקאי, למרגלות הר פוג'י. המוזיאון מציג את חיי הכפר היפני המסורתי ומציע חוויה אותנטית ושקטה במקום בית חווה מסורתי עם גג קש. תצוגות של כלי עבודה חקלאיים, כלי בית וכלי נשק סמוראיים. ומעיינות שקופים עם דגי קוי (ביקור כשעה ורבע, כניסה לכלל האיזור ¥300)", fee:{amount:300,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ]
    },
    {
      id: "day-20", date: "2026-04-05", dayOfWeek: "ראשון", title: "פוג'י והאגמים – יום שני", city: "פוג'י", cityEn: "Fuji", color: "#2196F3",
      hotel: { name: "RAKAYUYU ריוקאן", mapsQuery: "RAKAYUYU+Kawaguchiko+Japan" },
      items: [
        { id:"d20-a1", type:"activity", time:"", emoji:"🏡", title:"מוזיאון פתוח Hannoki Bayashi", titleEn:"Hannoki Bayashi Shiryokan Oshino Hakkai", mapsQuery:"Hannoki+Bayashi+Shiryokan+Oshino+Hakkai+Japan", description:"פתיחת היום בפנינה תרבותית בלב כפר המעיינות אושינו האקקאי, למרגלות הר פוג'י. המוזיאון מציג את חיי הכפר היפני המסורתי – בית חווה מסורתי עם גג קש, תצוגות כלי עבודה חקלאיים, כלי בית וכלי נשק סמוראיים. מעיינות שקופים עם דגי קוי (ביקור כשעה ורבע, כניסה ¥300)", fee:{amount:300,currency:"yen",perPerson:true}, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d20-a2", type:"activity", time:"", emoji:"🏯", title:"פגודת צ'ורייטו – תצפית איקונית על הר פוג'י", titleEn:"Chureito Pagoda Fujiyoshida", mapsQuery:"Chureito+Pagoda+Fujiyoshida+Japan", description:"ממשיכים את היום בטיפוס של כ-400 מדרגות לאחת הנקודות המצולמות ביותר ביפן – פגודה אדומה על רקע מושלם של הר פוג'י, עם עצים ירוקים פרוסים למרגלות ההר. הנוף למעלה עוצר נשימה – שווה כל טיפוס. מומלץ להגיע מוקדם כדי לתפוס את ההר כשהשמיים עוד פתוחים", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d20-r1", type:"restaurant", time:"", emoji:"🍜", title:"אטריות הוטו", titleEn:"Hoto Fudou Kawaguchiko", mapsQuery:"Hoto+Fudou+Kawaguchiko+Japan", description:"אם מטיילים באזור פוג'י ומחפשים אוכל מקומי אמיתי – המנה הכי מזוהה עם המחוז היא הוטו (Hoto Noodles). אטריות עבות ורכות שמבושלות בתוך מרק מיסו סמיך עם ירקות שורש, דלעת, כרוב ומרכיבים עונתיים נוספים. Hoto Fudou היא אחת הפופולריות ביותר – מגישים את ההוטו בקערות חימר מסורתיות שממשיכות לשמור על החום", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d20-a3", type:"activity", time:"", emoji:"🌬", title:"מערת הרוח פוגאקו", titleEn:"Fugaku Wind Cave Kawaguchiko", mapsQuery:"Fugaku+Wind+Cave+Kawaguchiko+Japan", description:"עולם נסתר מתחת לפני הקרקע – מערת לבה מרשימה שנוצרה בהתפרצות הר געש לפני מאות שנים. בקיץ שוררת טמפרטורה קרירה של כ-3 מעלות, ותוכלו לראות עמודי קרח טבעיים, מבני לבה מעניינים בצורת חבלים. אל תשכחו להציץ לעומק ולגלות את 'זהב הדרקון' – אזוב שמאיר בירוק מסתורי (הביקור 20-30 דקות)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d20-a4", type:"activity", time:"", emoji:"♨", title:"ערב בריוקאן", titleEn:"RAKAYUYU Ryokan", mapsQuery:"RAKAYUYU+Kawaguchiko+Japan", description:"חזרה לריוקאן לערב רגוע עם אונסן. אני ממליץ לשכור אונסן פרטי – החוויה בגדר חובה", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: ["מומלץ להגיע מוקדם לפגודת צ'ורייטו כדי לתפוס את ההר כשהשמיים עוד פתוחים"],
      appendix: [
        { id:"d20-x1", type:"activity", time:"", emoji:"🎢", title:"Fuji-Q Highland – אופציונלי", titleEn:"Fuji-Q Highland", mapsQuery:"Fuji-Q+Highland+Japan", description:"אם נשאר לכם כוח ואתם צמאים לריגושים – פארק השעשועים Fuji-Q שוכן ממש למרגלות הר פוג'י, מה שהופך את הרקע לתמונות לבלתי נשכח. לא חייב לרכוש כרטיס לכל הפארק, אפשר לרכוש גם פר מתקן", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ]
    },
    {
      id: "day-21", date: "2026-04-06", dayOfWeek: "שני", title: "שיבויה והאי המלאכותי אודאיבה", city: "טוקיו", cityEn: "Tokyo", color: "#E91E63",
      hotel: { name: "מלון בטוקיו", mapsQuery: "Tokyo+Hotel+Japan" },
      items: [
        { id:"d21-t1", type:"transport", time:"", emoji:"🚅", title:"חזרה לטוקיו", titleEn:"", mapsQuery:null, description:"צ'ק אאוט מהריוקאן ונסיעה חזרה לטוקיו", fee:null, bookInAdvance:false, line:"Bus + Train", from:"Kawaguchiko", to:"Tokyo", duration:"~2 שעות", transportNote:null },
        { id:"d21-a1", type:"activity", time:"", emoji:"🏖", title:"טיילת המרינה באודאיבה", titleEn:"Odaiba Marine Park Tokyo", mapsQuery:"Odaiba+Marine+Park+Tokyo+Japan", description:"ממשיכים בנסיעה לאודאיבה האי המלאכותי (קו Saikyō ירוק JA, לרדת ב-Tokyo Teleport Station). טיילת פתוחה עם נוף ישיר למפרץ טוקיו – מתאים גם לשבת על ספסל, לצלם ואפילו לשכשך את הרגליים במים (הקדישו כשעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d21-a2", type:"activity", time:"", emoji:"🎮", title:"JOYPOLIS – פארק VR מקורה", titleEn:"JOYPOLIS Odaiba Tokyo", mapsQuery:"JOYPOLIS+Odaiba+Tokyo+Japan", description:"עולם שלם של משחקי וידאו, סימולטורים ומתקנים אינטראקטיביים באווירה עתידנית. סימולטורים עם VR, מרוצי מכוניות, מתקני אימה דיגיטליים ומשחקי ארקייד נוצצים. המקום כולו מלא אורות ניאון, מוזיקה ואווירה יפנית עתידנית. שווה לקחת Free Pass כדי ליהנות מכל המתקנים (הקדישו כשעתיים)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d21-a3", type:"activity", time:"", emoji:"🤖", title:"קניון DiverCity Tokyo Plaza", titleEn:"DiverCity Tokyo Plaza Odaiba", mapsQuery:"DiverCity+Tokyo+Plaza+Odaiba+Japan", description:"הקניון שבחוץ מחכה רובוט גונדאם ענק בגובה 18 מטר – כל שעה הוא גם 'מתעורר לחיים'. בפנים – קומת אוכל, חנויות יפניות, חוויות VR ועוד. גם אם לא בקטע של קניות שווה לבקר בשביל האווירה. ממליץ על חנות בגדי הספורט בקומה הרביעית – מחירים מעולים (לפחות כשעה)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d21-a4", type:"activity", time:"", emoji:"🧠", title:"מיראקן – מוזיאון המדע", titleEn:"Miraikan National Museum Tokyo", mapsQuery:"Miraikan+National+Museum+Tokyo+Japan", description:"המוזיאון הלאומי למדע חדשני – מושלם למי שאוהב רובוטים, חלל וטכנולוגיה. תראו את הרובוטים המשולבי בינה מלאכותית, תצוגות אינטראקטיביות ומיצג דיגיטלי ענק של כדור הארץ. התערוכות מדברות על מגוון נושאים כמו הזדקנות, אסונות טבע, אנרגיות מתחדשות, גוף האדם ועוד (כשעתיים)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: [
        { id:"d21-x1", type:"activity", time:"", emoji:"🍣", title:"מסעדת סושירו – סושי מסוע", titleEn:"SUSHIRO Tokyo", mapsQuery:"SUSHIRO+Tokyo+Japan", description:"מסעדה שבה מזמינים סושי בטאבלט ומקבלים את הסושי עד אליכם במסוע תוך כמה דקות. העלויות מצחיקות וזו חוויה בגדר חובה ביפן (סניפים הרבה קיימים בטוקיו)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d21-x2", type:"activity", time:"", emoji:"🍲", title:"Shabu-Yo – הוטפוט בשיבויה", titleEn:"Shabu-Yo Shibuya Tokyo", mapsQuery:"Shabu-Yo+Shibuya+Tokyo+Japan", description:"מסעדת 'הוטפוט' בשיבויה – בוחרים בטאבלט סוגי מרק ובשר, מרכיבים תוספות מהבופה ומחכים למלצרובוט שיביא את הבשר. חוויה אמיתית, משביעה ויחסית לא יקרה (כ-80 שקלים לסועד)", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ]
    },
    {
      id: "day-22", date: "2026-04-07", dayOfWeek: "שלישי", title: "יום אחרון וטיסה הביתה", city: "טוקיו", cityEn: "Tokyo", color: "#E91E63",
      hotel: { name: "", mapsQuery: "" },
      items: [
        { id:"d22-a1", type:"activity", time:"", emoji:"🏨", title:"צ'ק אאוט מהמלון", titleEn:"", mapsQuery:null, description:"עזיבת המלון והכנת כל הציוד הדרוש להמראה. השארת המזוודות במלון", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d22-t1", type:"transport", time:"", emoji:"🚅", title:"נסיעה לשדה התעופה נריטה", titleEn:"", mapsQuery:null, description:"לקחת את רכבת הנריטה אקספרס מהמלון חזרה ומשם לשדה", fee:null, bookInAdvance:false, line:"Narita Express", from:"Tokyo", to:"Narita Airport", duration:"~1:30 שעות", transportNote:"יציאה בזמן בהתאם לשעת הטיסה" },
        { id:"d22-a2", type:"activity", time:"", emoji:"✈", title:"צ'ק-אין וביקורת גבולות", titleEn:"Narita International Airport", mapsQuery:"Narita+International+Airport+Japan", description:"מעבר בדיקות ביטחון, מסירת כבודה, ביקורת גבולות. חנויות דיוטי פרי", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null },
        { id:"d22-a3", type:"activity", time:"", emoji:"✈", title:"טיסה הביתה", titleEn:"Flight Home", mapsQuery:null, description:"להתראות יפן! 🇯🇵", fee:null, bookInAdvance:false, line:null, from:null, to:null, duration:null, transportNote:null }
      ],
      tips: [],
      appendix: []
    }
  ]
};
